services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/app
        depends_on:
            - php
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: Dockerfile
        command: /app/entrypoint.sh
        volumes:
            - ./:/app
        networks:
            - app-network

    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret123'
            MYSQL_USER: 'developer'
            MYSQL_PASSWORD: 'secret123'
            MYSQL_DATABASE: 'festivaldb'
        volumes:
            - mysqldata:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=secret123
        networks:
            - app-network
volumes:
    mysqldata:
networks:
    app-network:
        driver: bridge
